In [1]:
print('''파이썬
이스케
이프문
자실습''') #따옴표 한개는 인식안된덩

파이썬
이스케
이프문
자실습


In [1]:
txt ='파이썬오늘은\t문자열을\t배웠고,\t그\t지식을\t이용해서\t문자열\t수정을\t해\t봅시다.\n파이썬'
import re
txt_txt = ''.join(re.findall('[가-힣]+', txt))
txt_txt

'파이썬오늘은문자열을배웠고그지식을이용해서문자열수정을해봅시다파이썬'

In [4]:
txt2 = txt.split(',')
txt2
for i in txt2:
    print(i)

파이썬오늘은	문자열을	배웠고
	그	지식을	이용해서	문자열	수정을	해	봅시다.
파이썬


In [13]:
txt3 = txt.replace('파이썬', '')
print(txt3)

오늘은	문자열을	배웠고,	그	지식을	이용해서	문자열	수정을	해	봅시다.



In [18]:
txt0 = txt.replace("파이썬", '')
txt0 = txt0.replace("\t", '% ')
txt0 = txt0.replace(', %', ', % \n')
print(txt0)


오늘은% 문자열을% 배웠고,% 그% 지식을% 이용해서% 문자열% 수정을% 해% 봅시다.



In [22]:
for i in range(1,11):
    print('hello')
    print(i)
print('hello')

hello
1
hello
2
hello
3
hello
4
hello
5
hello
6
hello
7
hello
8
hello
9
hello
10
hello


In [35]:
#실습 1부터 10까지 숫자를 세는 프로그램을 만듯ㅂ니다

#단 숫자는 0.5 단위로 셉니다.

for i in range(1, 11):
    print(i)
    print(i+0.5)


1
1.5
2
2.5
3
3.5
4
4.5
5
5.5
6
6.5
7
7.5
8
8.5
9
9.5
10
10.5


In [40]:
a = int(input('숫자를 입력해주세요'))
for i in range(0, a, 2):
    print(i)

숫자를 입력해주세요8
0
2
4
6


In [11]:
a = int(input("숫자를 입력해주세요"))
result = 1
for i in range(1, a+1):
    result *= i
print(result)

숫자를 입력해주세요6
720


In [3]:
a = int(input())
i = 2
while i < a+2:
    if i % 2 == 0:
        print(i)
    i+=1
    

8
2
4
6
8


In [9]:
for abc in range(20):
    print(abc)
    continue
    print(456)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [10]:
for a in range(100):
    print(a)
    break
    print(5)
#패스는 그냥 말그대로 코드 다 돌릴 수 있음
#pass

0


In [7]:
for i in range(5):
    for j in range(5):
        print(i,j)

0 0
0 1
0 2
0 3
0 4
1 0
1 1
1 2
1 3
1 4
2 0
2 1
2 2
2 3
2 4
3 0
3 1
3 2
3 3
3 4
4 0
4 1
4 2
4 3
4 4


In [57]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]
for i in list1:
    for j in i:
        print(j, end= '')
    print()

123
456
789


In [59]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]
for i in list1:
    for j in i:
        print(j, end= ' ')

1 2 3 4 5 6 7 8 9 

In [20]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]
for i in list1:
    print(i, end='')

[1, 2, 3][4, 5, 6][7, 8, 9]

In [27]:
for i in range(5):
    print(i,end='')

01234

In [8]:
for i in range(5):
    for j in range(5):
        if j >= i :
            print('*', end='')
    print()
        

*****
****
***
**
*


In [12]:
for i in range(10):         
    for j in range(10):    
        if j == i:                 
            print(j, end='')
        else:
            print(' ', end='')
    print()

0         
 1        
  2       
   3      
    4     
     5    
      6   
       7  
        8 
         9


In [24]:
def f_factorial(n):
    if n>1:
        return n * f_factorial(n-1)
    else:
        return 1
a = int(input())
f_factorial(a)


4


24

######
NUMPY
파이썬의 배열 연산 패키지
ndarray 객체 지원
배열



# Numpy

In [27]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
arr+1

[1 2 3 4 5]


array([2, 3, 4, 5, 6])

In [36]:
list1 = [1,2,3,4,5,6,7,8,9]
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
arr[4]
#참고로 인덱스는 0부터임

5

In [38]:
list1[4:8]

[5, 6, 7, 8]

In [39]:
list1[-2:]

[8, 9]

In [40]:
list1[:-2]

[1, 2, 3, 4, 5, 6, 7]

In [43]:
list1[::3]

[1, 4, 7]

In [46]:
list1[-6:-1]

[4, 5, 6, 7, 8]

In [49]:
dict = {'key':'value', 'key2':'value2'}
dict

{'key': 'value', 'key2': 'value2'}

In [57]:
#슬라이싱 안됩니다
dict['key']

TypeError: unhashable type: 'slice'

In [60]:
arrray=np.array([1,2,3,4,5,6])

In [61]:
arrray[2]

3

In [62]:
arrray[2:4]

array([3, 4])

In [63]:
arrray[-3:4]

array([4])

In [64]:
arrray+5

array([ 6,  7,  8,  9, 10, 11])

# numpy 파읽 read, write

In [65]:
np.save('./numpy_title_npy', arrray) #압축파일

In [66]:
np.savez('./numpy_title_npz', arrray) #비압축 파일

In [73]:
import pandas as pd


In [77]:
pd.DataFrame([1,2,3,4,5], columns = ['df'])
#value, column, index

df
0   1
1   2
2   3
3   4
4   5

In [88]:
df = pd.DataFrame([[1,2,3,4,5], [4,5,6,7,8], [7,8,9,0,1]], index=['a', 'b', 'c']).T

In [85]:
pd.DataFrame([1,2,3,4,5])

0
0  1
1  2
2  3
3  4
4  5

In [89]:
df

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9
3  4  7  0
4  5  8  1

In [92]:
df.loc[4,'b']

8

In [93]:
df.loc[3]

a    4
b    7
c    0
Name: 3, dtype: int64

In [97]:
df.loc[:,'b':'c']
#이름기반 슬라이싱 location함수만 포함한덩 문자그대로까지 포함한다.


b  c
0  4  7
1  5  8
2  6  9
3  7  0
4  8  1

In [98]:
df.loc[2:4]
#대소관계를 비교할 수 없으므로 인덱스에 있는 것은 임의로 지정된 것

a  b  c
2  3  6  9
3  4  7  0
4  5  8  1

In [102]:
df.iloc[1:4, 0]
#얘는 범위 지정이 된다.
#인덱스자체는 포지션의 넘버이기에, n-1이 적용된다. 따라서 1-3까지

1    2
2    3
3    4
Name: a, dtype: int64

In [103]:
df.iloc[1:4] + 50

a   b   c
1  52  55  58
2  53  56  59
3  54  57  50

In [109]:
df.to_excel('./result1.xlsx', index=False, header=False)

In [120]:
pd.read_excel('./result1.xlsx', index_col=0, header=4)

Empty DataFrame
Columns: [8, 1]
Index: []

In [121]:
df.to_csv('./result3.csv')

In [126]:
a = df['c'] >=3
df[a]
#마스킹

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [130]:
df

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9
3  4  7  0
4  5  8  1

In [136]:
#인덱스를 대상으로 해서
n = df.loc[3] >= 4
df.loc[:, n]

a  b
0  1  4
1  2  5
2  3  6
3  4  7
4  5  8

In [180]:
a = df['c'] >=5
df2 = df[a]
df2


TypeError: 'DataFrame' object is not callable

In [181]:
m2 = df['c'] <= 8
df2[m2]

C:\Users\user\AppData\Local\Temp\ipykernel_11232\1680622931.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2[m2]


a  b  c
0  1  4  7
1  2  5  8

In [182]:
#query()
df.query('8>= c >=5')

a  b  c
0  1  4  7
1  2  5  8

# 과제
1. 판다스 패키지를 이용한다.
2. 각 column별로 (x+1) * 2 연산을 하기
3. 연산 결과는 'calc' column으로 따로 저장
4. (오늘 날짜).csv 파일로 내보내기