In [1]:
print('''파이썬
이스케
이프문
자실습''') #따옴표 한개는 인식안된덩

파이썬
이스케
이프문
자실습


In [6]:
txt ='파이썬오늘은\t문자열을\t배웠고,\t그\t지식을\t이용해서\t문자열\t수정을\t해\t봅시다.\n파이썬'
import re
txt_txt = ''.join(re.findall('[가-힣]+', txt))
txt_txt

'파이썬오늘은문자열을배웠고그지식을이용해서문자열수정을해봅시다파이썬'

In [9]:
txt2 = txt.split(',')
for i in txt2:
    print(i)

파이썬오늘은	문자열을	배웠고
	그	지식을	이용해서	문자열	수정을	해	봅시다.
파이썬


In [13]:
txt3 = txt.replace('파이썬', '')
print(txt3)

오늘은	문자열을	배웠고,	그	지식을	이용해서	문자열	수정을	해	봅시다.



In [18]:
txt0 = txt.replace("파이썬", '')
txt0 = txt0.replace("\t", '% ')
txt0 = txt0.replace(', %', ', % \n')
print(txt0)


오늘은% 문자열을% 배웠고,% 그% 지식을% 이용해서% 문자열% 수정을% 해% 봅시다.



In [22]:
for i in range(1,11):
    print('hello')
    print(i)
print('hello')

hello
1
hello
2
hello
3
hello
4
hello
5
hello
6
hello
7
hello
8
hello
9
hello
10
hello


In [35]:
#실습 1부터 10까지 숫자를 세는 프로그램을 만듯ㅂ니다

#단 숫자는 0.5 단위로 셉니다.

for i in range(1, 11):
    print(i)
    print(i+0.5)


1
1.5
2
2.5
3
3.5
4
4.5
5
5.5
6
6.5
7
7.5
8
8.5
9
9.5
10
10.5


In [40]:
a = int(input('숫자를 입력해주세요'))
for i in range(0, a, 2):
    print(i)

숫자를 입력해주세요8
0
2
4
6


In [11]:
a = int(input("숫자를 입력해주세요"))
result = 1
for i in range(1, a+1):
    result *= i
print(result)

숫자를 입력해주세요6
720


In [3]:
a = int(input())
i = 2
while i < a+2:
    if i % 2 == 0:
        print(i)
    i+=1
    

8
2
4
6
8


In [9]:
for abc in range(20):
    print(abc)
    continue
    print(456)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [10]:
for a in range(100):
    print(a)
    break
    print(5)
#패스는 그냥 말그대로 코드 다 돌릴 수 있음
#pass

0


In [13]:
for i in range(5):
    for j in range(5):
        print(i,j)
        

0 0
0 1
0 2
0 3
0 4
1 0
1 1
1 2
1 3
1 4
2 0
2 1
2 2
2 3
2 4
3 0
3 1
3 2
3 3
3 4
4 0
4 1
4 2
4 3
4 4


In [57]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]
for i in list1:
    for j in i:
        print(j, end= '')
    print()

123
456
789


In [59]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]
for i in list1:
    for j in i:
        print(j, end= ' ')

1 2 3 4 5 6 7 8 9 

In [20]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]
for i in list1:
    print(i, end='')

[1, 2, 3][4, 5, 6][7, 8, 9]

In [27]:
for i in range(5):
    print(i,end='')

01234

In [53]:
for i in range(5):
    for j in range(5):
        if j <= i :
            print('*', end='')
    print()
        

*
**
***
****
*****


In [50]:
for i in range(10):         
    for j in range(10):    
        if j == i:                 
            print('*', end='')
        else:
            print(' ', end='')
    print()

*         
 *        
  *       
   *      
    *     
     *    
      *   
       *  
        * 
         *


In [24]:
def f_factorial(n):
    if n>1:
        return n * f_factorial(n-1)
    else:
        return 1
a = int(input())
f_factorial(a)


4


24

######
NUMPY
파이썬의 배열 연산 패키지
ndarray 객체 지원
배열



# Numpy

In [27]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
arr+1

[1 2 3 4 5]


array([2, 3, 4, 5, 6])

In [36]:
list1 = [1,2,3,4,5,6,7,8,9]
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
arr[4]
#참고로 인덱스는 0부터임

5

In [38]:
list1[4:8]

[5, 6, 7, 8]

In [39]:
list1[-2:]

[8, 9]

In [40]:
list1[:-2]

[1, 2, 3, 4, 5, 6, 7]

In [43]:
list1[::3]

[1, 4, 7]

In [46]:
list1[-6:-1]

[4, 5, 6, 7, 8]

In [49]:
dict = {'key':'value', 'key2':'value2'}
dict

{'key': 'value', 'key2': 'value2'}

In [57]:
#슬라이싱 안됩니다
dict['key']

TypeError: unhashable type: 'slice'

In [60]:
arrray=np.array([1,2,3,4,5,6])

In [61]:
arrray[2]

3

In [62]:
arrray[2:4]

array([3, 4])

In [63]:
arrray[-3:4]

array([4])

In [64]:
arrray+5

array([ 6,  7,  8,  9, 10, 11])

# numpy 파읽 read, write

In [65]:
np.save('./numpy_title_npy', arrray) #압축파일

In [66]:
np.savez('./numpy_title_npz', arrray) #비압축 파일

In [73]:
import pandas as pd


In [77]:
pd.DataFrame([1,2,3,4,5], columns = ['df'])
#value, column, index

df
0   1
1   2
2   3
3   4
4   5

In [88]:
df = pd.DataFrame([[1,2,3,4,5], [4,5,6,7,8], [7,8,9,0,1]], index=['a', 'b', 'c']).T

In [85]:
pd.DataFrame([1,2,3,4,5])

0
0  1
1  2
2  3
3  4
4  5

In [89]:
df

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9
3  4  7  0
4  5  8  1

In [92]:
df.loc[4,'b']

8

In [93]:
df.loc[3]

a    4
b    7
c    0
Name: 3, dtype: int64

In [97]:
df.loc[:,'b':'c']
#이름기반 슬라이싱 location함수만 포함한덩 문자그대로까지 포함한다.


b  c
0  4  7
1  5  8
2  6  9
3  7  0
4  8  1

In [98]:
df.loc[2:4]
#대소관계를 비교할 수 없으므로 인덱스에 있는 것은 임의로 지정된 것

a  b  c
2  3  6  9
3  4  7  0
4  5  8  1

In [102]:
df.iloc[1:4, 0]
#얘는 범위 지정이 된다.
#인덱스자체는 포지션의 넘버이기에, n-1이 적용된다. 따라서 1-3까지

1    2
2    3
3    4
Name: a, dtype: int64

In [103]:
df.iloc[1:4] + 50

a   b   c
1  52  55  58
2  53  56  59
3  54  57  50

In [109]:
df.to_excel('./result1.xlsx', index=False, header=False)

In [120]:
pd.read_excel('./result1.xlsx', index_col=0, header=4)

Empty DataFrame
Columns: [8, 1]
Index: []

In [121]:
df.to_csv('./result3.csv')

In [126]:
a = df['c'] >=3
df[a]
#마스킹

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [130]:
df

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9
3  4  7  0
4  5  8  1

In [136]:
#인덱스를 대상으로 해서
n = df.loc[3] >= 4
df.loc[:, n]

a  b
0  1  4
1  2  5
2  3  6
3  4  7
4  5  8

In [180]:
a = df['c'] >=5
df2 = df[a]
df2


TypeError: 'DataFrame' object is not callable

In [181]:
m2 = df['c'] <= 8
df2[m2]

C:\Users\user\AppData\Local\Temp\ipykernel_11232\1680622931.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2[m2]


a  b  c
0  1  4  7
1  2  5  8

In [182]:
#query()
df.query('8>= c >=5')

a  b  c
0  1  4  7
1  2  5  8

# 과제
1. 판다스 패키지를 이용한다.
2. 각 column별로 (x+1) * 2 연산을 하기
3. 연산 결과는 'calc' column으로 따로 저장
4. (오늘 날짜).csv 파일로 내보내기

In [46]:
import numpy as np
import pandas as pd
data = {'A': [1, 2, 3, 4],
        'B': [5, 6, 7, 8],
        'C': [9, 10, 11, 12]}
df = pd.DataFrame(data)
df


A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [47]:
df0 = (df+1) * 2
df0

A   B   C
0   4  12  20
1   6  14  22
2   8  16  24
3  10  18  26

In [50]:
df0['calc'] = df0['A'] + df0['B'] + df0['C']
df0

A   B   C  calc
0   4  12  20    36
1   6  14  22    42
2   8  16  24    48
3  10  18  26    54

In [52]:
df0.to_csv("./20230920 김도현과제.csv")

In [ ]:
#공공데이터 포탈
#한국자산관리공사_국유부동산

In [9]:
import pandas as pd
df = pd.read_csv(r'C:\Users\user\dohyeon/한국자산관리공사_국유부동산 매각현황_20221231.csv', encoding ='cp949')
df


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141317 entries, 0 to 141316
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   연도구분        141317 non-null  int64  
 1   지역구분        141317 non-null  object 
 2   소재지명        141317 non-null  object 
 3   재산구분        141317 non-null  object 
 4   공부지목        141316 non-null  object 
 5   대장면적(제곱미터)  141317 non-null  float64
 6   대장금액(원)     141317 non-null  float64
 7   처분구분명       141317 non-null  object 
 8   계약일자        141317 non-null  object 
 9   부점명         141317 non-null  object 
 10  팀명          141232 non-null  object 
dtypes: float64(2), int64(1), object(8)
memory usage: 11.9+ MB


In [11]:
df

연도구분     지역구분                          소재지명 재산구분 공부지목  대장면적(제곱미터)  \
0       2014     전라북도              전라북도 정읍시 상동  725   토지    전        56.0   
1       2014    울산광역시           울산광역시 북구 천곡동  709-1   토지   임야       225.0   
2       2014     전라북도       전라북도 정읍시 산내면 종성리 727-21   토지    답       105.0   
3       2014     전라북도       전라북도 정읍시 산내면 종성리 727-16   토지    답       184.0   
4       2014     전라북도           전라북도 김제시 검산동  424-3   토지    전      2106.0   
...      ...      ...                           ...  ...  ...         ...   
141312  2022  제주특별자치도   제주특별자치도 서귀포시 표선면 하천리 1500-4   토지   임야       208.0   
141313  2022  제주특별자치도   제주특별자치도 서귀포시 표선면 세화리 2451-3   토지    전      1257.0   
141314  2022  제주특별자치도  제주특별자치도 서귀포시 표선면 세화리 2451-10   토지    전      2974.0   
141315  2022  제주특별자치도     제주특별자치도 서귀포시 표선면 토산리 32-3   토지   유지        80.0   
141316  2022  제주특별자치도     제주특별자치도 서귀포시 표선면 토산리 1033   토지   묘지       178.0   

            대장금액(원)     처분구분명        계약일자       부점명        팀명  
0         9968000.0  처분(매각수의)  2014-01-01    전북지역본부  국유재산관리1팀  
1        13770000.0  처분(매각수의)  2014-01-01   국유재산관리부     국유울산팀  
2         1075200.0  처분(매각수의)  2014-01-01    전북지역본부  국유재산관리1팀  
3         1884160.0  처분(매각수의)  2014-01-01    전북지역본부  국유재산관리1팀  
4        23797800.0  처분(매각수의)  2014-01-01    전북지역본부  국유재산관리2팀  
...             ...       ...         ...       ...       ...  
141312   29952000.0  처분(매각수의)  2022-11-09  광주전남지역본부    국유제주지사  
141313   56062200.0  처분(매각수의)  2022-12-29  광주전남지역본부    국유제주지사  
141314  132640400.0  처분(매각수의)  2022-12-29  광주전남지역본부    국유제주지사  
141315   32160000.0  처분(매각수의)  2022-08-04  광주전남지역본부    국유제주지사  
141316    2776800.0  처분(매각수의)  2022-11-22  광주전남지역본부    국유제주지사  

[141317 rows x 11 columns]

In [19]:
for c in df.columns:
    new_name = c + '_calc'
    try:
        df[new_name] = (df.loc[:, c] + 1) * 2
    except:
        pass


In [20]:
df

연도구분     지역구분                          소재지명 재산구분 공부지목  대장면적(제곱미터)  \
0       2014     전라북도              전라북도 정읍시 상동  725   토지    전        56.0   
1       2014    울산광역시           울산광역시 북구 천곡동  709-1   토지   임야       225.0   
2       2014     전라북도       전라북도 정읍시 산내면 종성리 727-21   토지    답       105.0   
3       2014     전라북도       전라북도 정읍시 산내면 종성리 727-16   토지    답       184.0   
4       2014     전라북도           전라북도 김제시 검산동  424-3   토지    전      2106.0   
...      ...      ...                           ...  ...  ...         ...   
141312  2022  제주특별자치도   제주특별자치도 서귀포시 표선면 하천리 1500-4   토지   임야       208.0   
141313  2022  제주특별자치도   제주특별자치도 서귀포시 표선면 세화리 2451-3   토지    전      1257.0   
141314  2022  제주특별자치도  제주특별자치도 서귀포시 표선면 세화리 2451-10   토지    전      2974.0   
141315  2022  제주특별자치도     제주특별자치도 서귀포시 표선면 토산리 32-3   토지   유지        80.0   
141316  2022  제주특별자치도     제주특별자치도 서귀포시 표선면 토산리 1033   토지   묘지       178.0   

            대장금액(원)     처분구분명        계약일자       부점명        팀명  연도구분_calc  \
0         9968000.0  처분(매각수의)  2014-01-01    전북지역본부  국유재산관리1팀       4030   
1        13770000.0  처분(매각수의)  2014-01-01   국유재산관리부     국유울산팀       4030   
2         1075200.0  처분(매각수의)  2014-01-01    전북지역본부  국유재산관리1팀       4030   
3         1884160.0  처분(매각수의)  2014-01-01    전북지역본부  국유재산관리1팀       4030   
4        23797800.0  처분(매각수의)  2014-01-01    전북지역본부  국유재산관리2팀       4030   
...             ...       ...         ...       ...       ...        ...   
141312   29952000.0  처분(매각수의)  2022-11-09  광주전남지역본부    국유제주지사       4046   
141313   56062200.0  처분(매각수의)  2022-12-29  광주전남지역본부    국유제주지사       4046   
141314  132640400.0  처분(매각수의)  2022-12-29  광주전남지역본부    국유제주지사       4046   
141315   32160000.0  처분(매각수의)  2022-08-04  광주전남지역본부    국유제주지사       4046   
141316    2776800.0  처분(매각수의)  2022-11-22  광주전남지역본부    국유제주지사       4046   

        대장면적(제곱미터)_calc  대장금액(원)_calc  
0                 114.0    19936002.0  
1                 452.0    27540002.0  
2                 212.0     2150402.0  
3                 370.0     3768322.0  
4                4214.0    47595602.0  
...                 ...           ...  
141312            418.0    59904002.0  
141313           2516.0   112124402.0  
141314           5950.0   265280802.0  
141315            162.0    64320002.0  
141316            358.0     5553602.0  

[141317 rows x 14 columns]

In [23]:
df.to_csv('230921.csv', encoding = 'cp949')

In [22]:
df['연도구분_calc']

0         4030
1         4030
2         4030
3         4030
4         4030
          ... 
141312    4046
141313    4046
141314    4046
141315    4046
141316    4046
Name: 연도구분_calc, Length: 141317, dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141317 entries, 0 to 141316
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   연도구분        141317 non-null  int64  
 1   지역구분        141317 non-null  object 
 2   소재지명        141317 non-null  object 
 3   재산구분        141317 non-null  object 
 4   공부지목        141316 non-null  object 
 5   대장면적(제곱미터)  141317 non-null  float64
 6   대장금액(원)     141317 non-null  float64
 7   처분구분명       141317 non-null  object 
 8   계약일자        141317 non-null  object 
 9   부점명         141317 non-null  object 
 10  팀명          141232 non-null  object 
dtypes: float64(2), int64(1), object(8)
memory usage: 11.9+ MB


In [10]:
df.isnull().sum()

연도구분           0
지역구분           0
소재지명           0
재산구분           0
공부지목           1
대장면적(제곱미터)     0
대장금액(원)        0
처분구분명          0
계약일자           0
부점명            0
팀명            85
dtype: int64